#########################
# Site Basics

title: discountdeadcats blog
description: A minimal blog to share my projects
url: "https://discountdeadcats.github.io"
baseurl: "" # Leave blank for GitHub Pages root
permalink: /blog/:slug/
timezone: America/New_York
future: false

#########################
# Plugins and Markdown

plugins:
  - jekyll-redirect-from

markdown: kramdown

#########################
# HTML Compression

compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

#########################
# Sass (optional, enable if using Sass stylesheets)

# sass:
#   sass_dir: css
#   style: compressed

#########################
# Collections (e.g., tags or categories)

collections:
  my_tags:
    output: true
    permalink: /tagged/:slug/

defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: tagged

#########################
# Navigation Links (optional)

links:
  # Resume: /assets/resume.pdf

special_links:
  # "Search": https://duckduckgo.com

#########################
# GitHub Pages Compatibility

exclude:
  - README.md
  - LICENSE.md
  - vendor
